### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by kbenoit** [quanteda/tutorials.quanteda.io#31]
Should we rename this repo **tutorials.quanteda.io** ?

**Comment by stefan-mueller** [comment]
I think we can rename the repo to **tutorials.quanteda.io**. If @koheiw agrees, I will check all links on the website (some refer to the **quanteda_tutorials** GitHub repo) and make a PR.

**Comment by stefan-mueller** [comment]
I created a new [branch](https://github.com/quanteda/quanteda_tutorials/tree/update-links) where I updated the URLs from `http://github.com/quanteda/quanteda_tutorials/...` to `https://github.com/quanteda/tutorials.quanteda.io/...`.

@koheiw, could you have a look at this, make changes if necessary, rename the repo, rebuild the website, and make a PR?
