### ISSUE TITLE
Update and extend Quanteda tutorials

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/tutorials.quanteda.io#50]
Now that **quanteda** v2 is on CRAN, @koheiw and I should use this opportunity to revise, edit, and – if necessary – extend the Quanteda tutorials pages. In particular, we should add more explanations and comments to the chapters and check whether v2 allows implementing some of the operations more efficiently.

**Comment by kbenoit** [comment]
Great idea, hopefully it can be rebuilt and then you can check for errors. If I can help with an audit let me know. (But @koheiw knows all the changed bits as well as I do.)
