### ISSUE TITLE
Tutorial as pdf?

### ISSUE THREAD

**Issue by werkstattcodes** [quanteda/tutorials.quanteda.io#77]
Apologies if this is not the right place to ask, but I was wondering whether it's a way to get a pdf version of the tutorial website. Many thanks, also for this wonderful package.

**Comment by koheiw** [comment]
There is no PDF version, but you can download all the Rmd files (in `/cotnent` ) to use offline.

https://github.com/quanteda/tutorials.quanteda.io/archive/master.zip

If you really want PDF files, you could even knit Rmd to PDF...

**Comment by werkstattcodes** [comment]
Thank you!
