### ISSUE TITLE
textstat_dist fails with Error in validityMethod(as(object, superClass))

### ISSUE THREAD

**Issue by enzedonline** [quanteda/tutorials.quanteda.io#88]
I'm trying to run the code on the tutorial page for [DOCUMENT/FEATURE SIMILARITY](https://github.com/quanteda/tutorials.quanteda.io/tree/master/content/statistical-analysis/dist.markdown)

```
require(quanteda)
require(quanteda.textstats)
toks_inaug <- tokens(data_corpus_inaugural)
dfmat_inaug <- dfm(toks_inaug, remove = stopwords("en"))
tstat_dist <- as.dist(textstat_dist(dfmat_inaug))
clust <- hclust(tstat_dist)
plot(clust, xlab = "Distance", ylab = NULL)
```

The call to textstat_dist triggers the following error:

```
Error in validityMethod(as(object, superClass)) : 
  object 'packedMatrix_validate' not found
```

Solutions tried:

Clearing workspace & restarting R for clean environment.

First I've tried removing punctuation from the tokens, then fixing the dfm call to remove the stop words (as this doesn't seem to be valid):
```
toks_inaug <- tokens(data_corpus_inaugural, remove_punct = T)
dfmat_inaug <- dfm_remove(dfm(toks_inaug), pattern = stopwords("en"))
```

Same error. Also tried just calling `textstat_dist(dfmat_inaug)` directly (without `as.dist`).

I doubled checked the class of dfmat_inaug and checked it had valid data:

```
class(dfmat_inaug)
[1] "dfm"
attr(,"package")
[1] "quanteda"
topfeatures(dfmat_inaug, 10)
    people government         us        can       must       upon      great        may     states 
       584        564        505        487        376        371        344        343        334 
     world 
       319 
```

I've also tried some of the other data_corpus data sets from textstats, same again.

I notice when I load the quanteda library, I get the following warning messages:

```
require(quanteda)
Loading required package: quanteda
Package version: 3.2.1
Unicode version: 13.0
ICU version: 69.1
Parallel computing: 4 of 4 threads used.
See https://quanteda.io for tutorials and examples.
Warning messages:
1: In .recacheSubclasses(def@className, def, env) :
  undefined subclass "packedMatrix" of class "replValueSp"; definition not updated
2: In .recacheSubclasses(def@className, def, env) :
  undefined subclass "packedMatrix" of class "mMatrix"; definition not updated
```

System:

Win10 x64
R4.1.3
quanteda 3.2.1

All packages as per [https://tutorials.quanteda.io/introduction/install/](https://tutorials.quanteda.io/introduction/install/) installed with latest versions.

**Comment by enzedonline** [comment]
I ran into the same problem again on the [twitter example](https://tutorials.quanteda.io/advanced-operations/twitter-user-similarity/)

**Comment by kbenoit** [comment]
Try `update.packages()`, since this is working fine for me.

``` r
require(quanteda)
#> Loading required package: quanteda
#> Package version: 3.2.1
#> Unicode version: 13.0
#> ICU version: 67.1
#> Parallel computing: 10 of 10 threads used.
#> See https://quanteda.io for tutorials and examples.
require(quanteda.textstats)
#> Loading required package: quanteda.textstats
toks_inaug <- tokens(data_corpus_inaugural)
dfmat_inaug <- dfm(toks_inaug, remove = stopwords("en"))
#> Warning: 'remove' is deprecated; use dfm_remove() instead
tstat_dist <- as.dist(textstat_dist(dfmat_inaug))
clust <- hclust(tstat_dist)
plot(clust, xlab = "Distance", ylab = NULL)
```

![](https://i.imgur.com/6jPe1jJ.png)

<sup>Created on 2022-04-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AngusMackenzie** [comment]
Hi @enzedonline, I had a similar problem when trying to use textstat_simil. I also was getting the same warning when loading the quanteda package:

Warning messages:
1: In .recacheSubclasses(def@className, def, env) :
  undefined subclass "packedMatrix" of class "replValueSp"; definition not updated
2: In .recacheSubclasses(def@className, def, env) :
  undefined subclass "packedMatrix" of class "mMatrix"; definition not updated

What I did to resolve the issue was to update all my other packages and the problem went away.
